# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Python flake8 Lint
        # You may pin to the exact commit or the version.
        uses: py-actions/flake8@v2.2.1
          
      - name: Mypy Check
        # You may pin to the exact commit or the version.
        # uses: jpetrucciani/mypy-check@f7a31184677eec02e0683cc0d31c5d5331d5ab5c
        uses: jpetrucciani/mypy-check@0.991
